### ISSUE TITLE
Decide dOrg Token Staking APR

### ISSUE THREAD

**Issue by nestorbe** [dOrgTech/token-redemption#10]
Hello guys!

I need your comment about this, the dOrg token redemption/staking app is almost ready for launch but in order to deploy the contracts we need to decide what the staking APR for the dOrg token is going to be. 

Here you can check the contract that handle's the staking rewards for the token:

[StakingReward.sol](https://github.com/dOrgTech/token-redemption/blob/master/packages/protocol/contracts/reward/StakingReward.sol)

Thank you,

**Comment by benefacto** [comment]
Hi Nestor, this is really great work that you've been doing! I appreciate that you've just stepped up on this project as it was sorely needed. I have a few non-technical questions that would be involved in a consideration of an APR:
- Do we have a picture of what dOrg's current outstanding debt would be given a few example APRs figures? Or are we assuming that staking only counts in the future once these contracts are deployed and users stake?
- Do we have any built-in mechanism to prevent a run on dOrg's reserve besides the incentive to stake? Currently, if there was one, [dOrg's reserve](https://docs.google.com/spreadsheets/d/1mwYhzTNXSytzVtACZLu1V_EVTfjPKhGfHu-KhnBFESk/edit?usp=sharing) could be very quickly depleted.

**Comment by nestorbe** [comment]
Thank you very much @benefacto !

Regarding your questions, I can't give you an exact answer for them. I guess we could do the calculations with examples and see a more clear picture. Maybe @dOrgJelli or @orishim have more information about this.

**Comment by dOrgJelli** [comment]
- Staking would only count for the future @benefacto, so the outstanding debt will remain untouched.
- These contracts do not draw from dOrg's reserves directly. Additionally it's up to dOrg to "refill" the rewards contract with addition dOrg tokens, allowing stakers to redeem their rewards. So in short, the process of managing the rewards & redemption contracts from the DAO's perspective looks like:
    - Vote to send more dOrg tokens to the StakingRewards contract (adding more debt + giving more rewards to stakers to claim over time)
    - Vote to set the APR on the StakingRewards contract (incentivizes staking)
    - Vote to send stable coins to the StableRedemption contract (allowing dOrg holders to "cash in")

**Comment by benefacto** [comment]
> 
> 
>     * Staking would only count for the future @benefacto, so the outstanding debt will remain untouched.
> 
>     * These contracts do not draw from dOrg's reserves directly. Additionally it's up to dOrg to "refill" the rewards contract with addition dOrg tokens, allowing stakers to redeem their rewards. So in short, the process of managing the rewards & redemption contracts from the DAO's perspective looks like:
>       
>       * Vote to send more dOrg tokens to the StakingRewards contract (adding more debt + giving more rewards to stakers to claim over time)
>       * Vote to set the APR on the StakingRewards contract (incentivizes staking)
>       * Vote to send stable coins to the StableRedemption contract (allowing dOrg holders to "cash in")

Thanks for the answers! That alleviates my concerns. I'm not sure what a good APR would be but given how this would work, it sounds like it can be chosen relatively arbitrarily.

**Comment by dOrgJelli** [comment]
Yah it's based on how much dOrg wants to incentivize staking for longer term. I think something around 25% sounds good, since most stable coin staking protocols (CRV for example) are rewarding around that rate. This would make dOrg tokens very competitive with stable coins, and give people less of a reason to cash them out immediately.

**Comment by nestorbe** [comment]
After researching about this matter, I think anything between 10-30% APR sounds fair and it's what most stable coin staking protocols are offering. As @dOrgJelli said, this number can vary depending on how much dOrg wants token holders to stake for longer term based on the current amount of DORG tokens out there (we can always change the APR as needed with the "setAPR" method in the contract that is going to be owned by the DAO).

20-25% is not a bad option to deploy the contract and incentivize holders to keep the tokens and stake.

**Comment by orishim** [comment]
All of the stable coin yearn vaults are currently yielding between 10-15%. I'm not familiar with anything higher on stable coins.

I think this is something we should be incredibly conservative with as we could easily flood ourselves into debt. Keep in mind this is not a public offering that we are looking to attract public capital into. We don't have to compete with those rates. This is for dOrg members who want to help the organization they are a part of sustain itself in hard times and grow faster in good times. 

I would start at 2-4%, which is still far higher than the traditional world where high-yield savings accounts are currently yielding 0.5%. We can always raise it if we think this is not effective enough.

**Comment by rihp** [comment]
Amazing work Nestor. I agree that starting this on the low APY spectrum is better for starters. (Less than 5%, test, and reevaluate later down the road). Another idea is to consider Lending platforms like Compound, Aave, which also have similar APYs for the user.

Would we deploy this in xDAI ?

**Comment by dOrgJelli** [comment]
Unfortunately we can't deploy on xDAI since the contract only supports ERC20s :/ is this something we should fix? Shouldn't be too hard.

**Comment by nestorbe** [comment]
I think if it's possible to deploy it on xDAI we should try and go for it, with current gas prices it makes more sense for this dApp.
